// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppButton: typeof import('./src/components/AppButton.vue')['default']
    AppImage: typeof import('./src/components/AppImage.vue')['default']
    AppPageHeading: typeof import('./src/components/AppPageHeading.vue')['default']
    BoardCard: typeof import('./src/components/BoardCard.vue')['default']
    BoardDragAndDrop: typeof import('./src/components/BoardDragAndDrop.vue')['default']
    ImageDropzone: typeof import('./src/components/ImageDropzone.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheDrawer: typeof import('./src/components/TheDrawer.vue')['default']
    TheNavBar: typeof import('./src/components/TheNavBar.vue')['default']
  }
}

export {}
